### ISSUE TITLE
创建文件的过程，用户无感知。在点击“confirm”按钮后，发现文件还没创建，就以为创建失败了。建议优化一下。

### ISSUE THREAD

**Issue by TigerLau** [BakerJQ/FishReduxTemplateForAS#1]

**Comment by BakerJQ** [comment]
问题已修复，可以的话能否帮忙验证下，如果还是不行，能否提供下你的AS版本号，以及是PC还是Mac

**Comment by Miverk** [comment]
我用最新版的还是会这样，等了好久， AS3.3  插件版本1.2
page.dart 里面 middleware少了一个s

**Comment by Miverk** [comment]
用的PC

**Comment by BakerJQ** [comment]
最新版的FishRedux去掉了middleware后面的s，关于创建文件的，我再看看吧

**Comment by BakerJQ** [comment]
你现在可以创建完后，先通过刷新文件夹的方式用用。。。
<img width="321" alt="image" src="https://user-images.githubusercontent.com/11451739/55462596-b3b2d400-5629-11e9-9d1b-f465b5ebbe10.png">
