### ISSUE TITLE
fish redux 0.1.3报错

### ISSUE THREAD

**Issue by MMMzq** [BakerJQ/FishReduxTemplateForAS#2]
在生成adapter模板时，adapter.dart文件报错，原因时fish redux更新后Connectord被弃用了且多了subReducer方法

**Comment by MMMzq** [comment]
且adapter.dart文件中 import '../state.dart';  多了一个点

**Comment by MMMzq** [comment]
建议改一下 "cancle",“confirm”两个按钮的颜色，不要用灰色，不然容易误导用户是这两个按钮禁用的。

**Comment by BakerJQ** [comment]
谢谢你提的问题和建议

**Comment by BakerJQ** [comment]
已做调整，plugin repo还在等待审核，可以安装jar包使用
