### ISSUE TITLE
module name 没法输入

### ISSUE THREAD

**Issue by tom1918** [BakerJQ/FishReduxTemplateForAS#3]
![image](https://user-images.githubusercontent.com/6824136/55206335-08f97a80-5211-11e9-9ac2-f27a63dc0ab4.png)

我的 android studio 的版本是 3.1.2

**Comment by BakerJQ** [comment]
这个问题是输入框长度设置问题，最新版本已经改了，正在审核中

**Comment by BakerJQ** [comment]
审核已通过，可以到AS的plugin repo里搜索安装
<img width="818" alt="image" src="https://user-images.githubusercontent.com/11451739/55223104-6fe65600-5248-11e9-89bb-bca2ad5e818c.png">

**Comment by tom1918** [comment]
> 审核已通过，可以到AS的plugin repo里搜索安装
> <img alt="image" width="818" src="https://user-images.githubusercontent.com/11451739/55223104-6fe65600-5248-11e9-89bb-bca2ad5e818c.png">

感谢分享，我更新试试~
