### ISSUE TITLE
安装了插件,但是没有功能

### ISSUE THREAD

**Issue by shenqidebaozi** [BakerJQ/FishReduxTemplateForAS#5]
安装了插件,但是new菜单里面没有插件的按钮

**Comment by shenqidebaozi** [comment]
![image](https://user-images.githubusercontent.com/35397691/56335919-f26f8f00-61d0-11e9-94c5-a7821e24d0c6.png)

**Comment by BakerJQ** [comment]
1、是否重启了AS
2、对lib下面的包操作试试
如果还没有用的话，麻烦给一下AS版本、平台等信息，谢谢

**Comment by shenqidebaozi** [comment]
![image](https://user-images.githubusercontent.com/35397691/56336631-abcf6400-61d3-11e9-9831-0ca629510020.png)
重启了AS没反应,插件已经装好了
![image](https://user-images.githubusercontent.com/35397691/56336648-bf7aca80-61d3-11e9-86c8-c5a737c9cb50.png)
****
![image](https://user-images.githubusercontent.com/35397691/56336659-cacdf600-61d3-11e9-8077-24d3f2a036f2.png)
flutter版本1.2.1

**Comment by BakerJQ** [comment]
android studio什么版本

**Comment by shenqidebaozi** [comment]
第一个图上有详细的

**Comment by BakerJQ** [comment]
新版本已提交
